def evenFibonacciNumbers():
    """
    Each new term in the Fibonacci sequence is generated by adding t
    he previous two terms. By starting with 1 and 2, the first 10 
    terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values 
    do not exceed four million, find the sum of the even-valued terms.
    """
    a, b, p = 0, 0, 1
    fibo = []
    for i in range(0, 1_000_000):
        if p > 4_000_000:
            break
        a = b
        b = p
        p = a + b
        if p % 2 == 0:
            fibo.append(p)
    print(sum(fibo))


evenFibonacciNumbers()
